export const FETCH_ORG_REPOS = 'fetch_org_repos'
export const FETCH_ORG_REPOS_SUCCESS = 'fetch_org_repos_success'
export const FETCH_ORG_REPOS_FAILED = 'fetch_org_repos_failed'
export const FETCH_REPO_CONTRIBUTORS = 'fetch_repo'
export const FETCH_REPO_CONTRIBUTORS_SUCCESS = 'fetch_repo_success'
export const FETCH_REPO_CONTRIBUTORS_FAILED = 'fetch_repo_failed'
export const SET_REPOS_FILTER = 'set_repos_filter'
export const SELECT_REPO = 'select_repo'
